services:
  chaseisabelle_phprom_service:
    class: ChaseIsabelle\PHPromBundle\Service\PHPromService
    arguments:
      - '127.0.0.1:3333',
      - 'phprom'
  chaseisabelle_phprom_subscriber:
    class: ChaseIsabelle\PHPromBundle\EventSubscriber\PHPromEventSubscriber
    arguments:
      - '@phprom_service'
    tags:
      - { name: kernel.event_subscriber, event: kernel.request, method: onKernelRequest }
      - { name: kernel.event_subscriber, event: kernel.response, method: onKernelResponse }
      - { name: kernel.event_subscriber, event: kernel.finish_request, method: onKernelFinishRequest }

